### ISSUE TITLE
Script interferes with homebrew's update blocking feature

### ISSUE THREAD

**Issue by DpunktKpunkt** [tf318/lg#2]
My TV is rooted and I'm using homebrew channel, including enabled ssh and blocked updates.
Unfortunately your script interfered with homebrew's method of blocking firmware updates (it copies /etc/hosts to tmp, then tries to bind mounts it), thus updates were found.

I changed your init.d script so it works the same way:

> cp /etc/ca-certificates.conf /tmp/ca-certificates.conf
> mount --bind /tmp/ca-certificates.conf /etc/ca-certificates.conf
> echo 'lets-encrypt-r3.crt' >> /etc/ca-certificates.conf
> echo 'isrgrootx1.crt' >> /etc/ca-certificates.conf
> 
> mount -t overlay overlay -o lowerdir=/etc/ssl,upperdir=/home/certfix-overlay/etc/ssl,workdir=/home/certfix-overlay/work-etc_ssl /etc/ssl
> mount -t overlay overlay -o lowerdir=/usr/share/ca-certificates,upperdir=/home/certfix-overlay/usr_share_ca-certificates,workdir=/home/certfix-overlay/work-usr_share_ca-certificates /usr/share/ca-certificates
> update-ca-certificates

**Comment by tf318** [comment]
Thanks for highlighting this issue. Fixed.

**Comment by tf318** [comment]
Thanks for highlighting this issue. Fixed.
