### ISSUE TITLE
No app updates after running script

### ISSUE THREAD

**Issue by Lasermachete** [tf318/lg#3]
Hello,

thanks for the script it worked well for me. Since in ran it, i can't updates on the standard apps like netflix etc. Is there a way to solve this?

Thanks

**Comment by tf318** [comment]
Hi there - the script simply removes an expired CA root certificate (any connections to hosts that had certificates signed by that old certificate would fail even if this were not removed), and adds new LetsEncrypt CA root certificates (which allows additional connections to hosts with certificates signed by the new LetsEncrypt CA root certificates). 

The script does not affect application updates in any way. I have no trouble updating apps on my TV, on which this script has run multiple times for testing. Could you be having a temporary network issue?
